import {KEY,RESOURCES,PROJECTS,loadCity,wallet,award,build,pave,expand,canExpand,canBuild,migrateHousing} from '../shared/city-state.mjs';
import {drawProp,drawCrew,drawResident,onSpritesReady} from './makko-sprites.mjs';
import {apartmentTile,onArtReady} from './art-renderer.mjs';
const $=s=>document.querySelector(s),labels={housing:'Building supplies',streets:'Street work',recreation:'Court points',care:'Neighbors helped',policy:'Civic wins'},reduced=matchMedia('(prefers-reduced-motion: reduce)');
let storage;try{storage=localStorage;}catch{}
let city=loadCity(storage),selected=city.blocks.length-1,failed=false,last=0,visible=true;
function save(){try{storage.setItem(KEY,JSON.stringify(city));failed=false;return true;}catch{failed=true;return false;}}
if(migrateHousing(city,storage))save();
if(location.hash.startsWith('#rewards=')){try{const events=JSON.parse(decodeURIComponent(location.hash.slice(9)));if(Array.isArray(events)&&events.length<=1000){for(const e of events)if(['crashers:help','crashers:policy'].includes(e?.type))award(city,e);if(save())history.replaceState(null,'',location.pathname+location.search);}}catch{}}
function render(){
 $('#city-name').textContent=city.name;$('#opt-in').hidden=city.optedIn;$('#builder').hidden=!city.optedIn;$('#save-status').textContent=failed?'Saving unavailable. Keep this page open; your latest changes may not survive a reload.':'Saved in this browser · account saving across devices is not available yet.';
 const b=city.blocks[selected],w=wallet(city);$('#block-title').textContent='Block '+(selected+1)+' · '+['Stoop Street','Garden Avenue','Courtyard Row'][selected%3];$('#scale').textContent='Neighborhood '+(Math.floor(selected/3)+1)+' · Borough '+(Math.floor(selected/9)+1)+' · '+city.blocks.length+' blocks opened';$('#previous').disabled=selected===0;$('#next').disabled=selected===city.blocks.length-1;
 $('#wallet').replaceChildren(...RESOURCES.map(k=>{const d=document.createElement('div'),n=document.createElement('strong'),l=document.createElement('span');n.textContent=w[k];l.textContent=labels[k];d.append(n,l);return d;}));
 $('#capacity').textContent=b.lots.length+'/6 lots built. '+(b.road?'The street is repaired.':'The street still needs work.');
 $('#projects').replaceChildren(...Object.entries(PROJECTS).map(([id,p])=>{const d=document.createElement('article');d.className='project';const h=document.createElement('h4'),desc=document.createElement('p'),cost=document.createElement('small'),button=document.createElement('button');h.textContent=p.name;desc.textContent=p.description;cost.textContent=Object.entries(p.cost).map(([k,n])=>n+' '+labels[k].toLowerCase()).join(' + ');button.textContent='Build →';button.disabled=!canBuild(city,id,selected);button.onclick=()=>{reload();if(build(city,id,selected)){save();$('#feedback').textContent=p.name+' built on Block '+(selected+1)+'.';render();}};d.append(h,desc,cost,button);return d;}));
 $('#pave').disabled=b.road||w.streets<6;$('#pave').textContent=b.road?'Street repaired ✓':'Repair this block’s street · 6 street work';$('#expand').disabled=!canExpand(city);$('#goal').textContent=canExpand(city)?'Your newest block is ready. Open another and keep the city growing.':'To open the next block: build four lots, including homes and a court, and repair its street. Three blocks form a neighborhood; nine form a borough.';
 draw(performance.now());
}
function reload(){if(storage)city=loadCity(storage);if(migrateHousing(city,storage))save();selected=Math.min(selected,city.blocks.length-1);}
$('#join').onclick=()=>{reload();city.name=$('#name').value.trim().slice(0,40)||'Our City';city.optedIn=true;save();render();};
$('#previous').onclick=()=>{selected=Math.max(0,selected-1);render();};$('#next').onclick=()=>{selected=Math.min(city.blocks.length-1,selected+1);render();};
$('#pave').onclick=()=>{reload();if(pave(city,selected)){save();$('#feedback').textContent='Cracks filled. A safer street for the whole block.';render();}};
$('#expand').onclick=()=>{reload();if(expand(city)){selected=city.blocks.length-1;save();$('#feedback').textContent='A new block is yours to build.';render();}};
window.addEventListener('storage',e=>{if([KEY,'pa-housing-city-v1'].includes(e.key)){reload();render();}});window.addEventListener('focus',()=>{reload();render();});document.addEventListener('visibilitychange',()=>{visible=!document.hidden;if(visible){reload();render();}});
function draw(now){if(!city.optedIn)return;const canvas=$('#city'),c=canvas.getContext('2d'),b=city.blocks[selected],t=reduced.matches?0:now/1000;c.clearRect(0,0,900,470);const sky=c.createLinearGradient(0,0,0,470);sky.addColorStop(0,'#87bfc7');sky.addColorStop(1,'#e4d3b5');c.fillStyle=sky;c.fillRect(0,0,900,470);c.fillStyle='#aab896';c.fillRect(0,210,900,260);c.fillStyle='#c7b8a0';c.fillRect(0,330,900,54);c.fillStyle=b.road?'#586779':'#544e46';c.fillRect(0,384,900,86);c.lineWidth=b.road?3:2;c.strokeStyle=b.road?'#eadfb7':'#2a2928';for(let x=25;x<900;x+=110){c.beginPath();if(b.road){c.moveTo(x,429);c.lineTo(x+55,429);}else{c.moveTo(x,397);c.lineTo(x+17,414);c.lineTo(x+4,428);c.lineTo(x+24,449);}c.stroke();}
 const locations=[80,225,370,515,660,805];for(let i=0;i<6;i++){const x=locations[i],feet=335,id=b.lots[i];if(!id){drawProp(c,4,x,feet,65,48);drawCrew(c,x+35,feet+15,i,t,'build',34);continue;}if(id==='homes'){for(let f=0;f<4;f++)for(let r=0;r<2;r++)apartmentTile(c,f===0&&r===1?8:(i+selected)%7,x-52+r*52,feet-(f+1)*52,52);for(let r=0;r<2;r++)apartmentTile(c,7,x-52+r*52,feet-245,52);}if(id==='park'){drawProp(c,0,x-15,feet,92,110);drawProp(c,1,x+35,feet+8,70,50);}if(id==='court'){drawProp(c,6,x,feet,136,160);}if(id==='fountain')drawProp(c,7,x,feet,114,145);if(id==='kitchen')drawProp(c,2,x,feet,95,130);if(id==='clinic'){for(let r=0;r<2;r++)apartmentTile(c,3,x-52+r*52,feet-52,52);c.fillStyle='#fff0cc';c.fillRect(x-38,feet-83,76,25);c.fillStyle='#b94542';c.font='bold 13px system-ui';c.textAlign='center';c.fillText('+ CLINIC',x,feet-65);}drawResident(c,x+15,feet+30,i,t,true,38);c.font='bold 12px system-ui';c.textAlign='center';c.fillStyle='#243441';c.fillText(PROJECTS[id].name.toUpperCase(),x,feet+49);}
 const n=Math.min(12,b.lots.length*2);for(let i=0;i<n;i++){const x=30+((t*17+i*71)%830);drawResident(c,x,382,i,t,false,34);}if(b.lots.length){drawProp(c,8,22,350,40,36);drawProp(c,8,878,350,40,36);}c.textAlign='left';c.fillStyle='#243441';c.font='bold 18px system-ui';c.fillText(city.name+' · BLOCK '+(selected+1),24,30);canvas.setAttribute('aria-label',city.name+', Block '+(selected+1)+': '+(b.lots.map(id=>PROJECTS[id].name).join(', ')||'empty lots')+'. '+(b.road?'Street repaired.':'Street cracked.'));
}
function frame(now){if(visible&&now-last>80){draw(now);last=now;}requestAnimationFrame(frame);}render();onSpritesReady(()=>draw(performance.now()));onArtReady(()=>draw(performance.now()));requestAnimationFrame(frame);
