(()=>{
 'use strict';
 const CENTRAL='https://politicalarcades.com',foreign=location.hostname.endsWith('capitolcrashers.com'),script=document.currentScript.src,queueKey='pa-city-reward-outbox-v1';
 let pending=[];try{pending=JSON.parse(localStorage.getItem(queueKey))||[];}catch{}if(!Array.isArray(pending))pending=[];
 const saveQueue=()=>{try{localStorage.setItem(queueKey,JSON.stringify(pending));}catch{}};
 let state,api,ready=false,storage;try{storage=localStorage;}catch{}
 const status=document.createElement('aside');status.className='city-reward-bar';status.innerHTML='<strong>Your city</strong><span data-city-status>All four games build one city.</span><a data-city-link href="'+CENTRAL+'/city/">Visit your city →</a>';
 const style=document.createElement('style');style.textContent='.city-reward-bar{box-sizing:border-box;max-width:1100px;margin:20px auto;padding:14px 18px;display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;background:#142b33;border:1px solid #5bc1ac70;border-radius:12px;color:#fff0cc;font:14px system-ui}.city-reward-bar a{color:#ffda78;font-weight:800}.city-reward-bar span{flex:1;min-width:170px}.city-reward-bar strong{color:#7fdbc2}';document.head.append(style);
 const mount=()=>{const footer=document.querySelector('footer');if(footer)footer.before(status);else document.body.append(status);};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
 const message=text=>status.querySelector('[data-city-status]').textContent=text;
 function link(){const a=status.querySelector('[data-city-link]');a.href=(foreign?CENTRAL:'')+'/city/'+(foreign&&pending.length?'#rewards='+encodeURIComponent(JSON.stringify(pending)):'');if(foreign)a.target='_top';}
 function flush(){if(!ready)return;state=api.loadCity(storage);let changed=api.migrateHousing(state,storage);for(const e of pending)changed=api.award(state,e)||changed;try{if(changed)storage.setItem(api.KEY,JSON.stringify(state));pending=[];saveQueue();}catch{message('City saving is unavailable in this browser.');return;}link();if(state.optedIn)message(state.name+' · '+state.blocks.length+' blocks · saved on this device');}
 function send(){if(foreign&&window.parent!==window)window.parent.postMessage({channel:'pa-city-v1',kind:'rewards',events:pending},CENTRAL);link();}
 window.CityRewards={credit(type,count=1){const e={id:crypto.randomUUID(),type,count};pending.push(e);saveQueue();if(foreign)send();else flush();message('Earned for your city · '+count+' '+({'pothole:repair':'street work','vote:basket':'court point','vote:win':'court points','crashers:help':'neighbor helped','crashers:policy':'civic win'}[type]||'building supplies'));return e.id;},syncHousing(){if(!foreign)flush();},flush};
 if(!foreign)import(new URL('city-state.mjs',script)).then(m=>{api=m;ready=true;flush();document.querySelector('[data-city-game]')?.contentWindow.postMessage({channel:'pa-city-v1',kind:'ready'},'https://capitolcrashers.com');}).catch(()=>message('City connection unavailable. Rewards are kept for your next visit.'));
 window.addEventListener('message',e=>{if(foreign){if(e.origin!==CENTRAL||e.source!==parent||e.data?.channel!=='pa-city-v1')return;if(e.data.kind==='ready')send();if(e.data.kind==='saved'&&Array.isArray(e.data.ids)){pending=pending.filter(v=>!e.data.ids.includes(v.id));saveQueue();link();message('Rewards delivered to your city.');}}else{const frame=document.querySelector('[data-city-game]');if(!frame||e.source!==frame.contentWindow||e.origin!=='https://capitolcrashers.com'||e.data?.channel!=='pa-city-v1'||e.data.kind!=='rewards'||!ready)return;const events=e.data.events;if(!Array.isArray(events)||events.length>1000)return;state=api.loadCity(storage);const ids=[];for(const v of events)if(['crashers:help','crashers:policy'].includes(v?.type)){if(api.award(state,v)||state.seen.includes(v.id))ids.push(v.id);}try{storage.setItem(api.KEY,JSON.stringify(state));e.source.postMessage({channel:'pa-city-v1',kind:'saved',ids},e.origin);message('Capitol Crashers rewards delivered to '+state.name+'.');}catch{message('Could not save city rewards.');}}});
 document.addEventListener('DOMContentLoaded',()=>{const frame=document.querySelector('[data-city-game]');frame?.addEventListener('load',()=>frame.contentWindow.postMessage({channel:'pa-city-v1',kind:'ready'},'https://capitolcrashers.com'));});
 window.addEventListener('pagehide',()=>{if(!foreign)flush();});link();
})();
