(() => {
  const root=document.createElement('div');root.className='mobile-ui';root.hidden=true;
  root.innerHTML=`<section class="mobile-menu" aria-label="VOTE mobile menu"><img class="mobile-logo" src="assets/ui/makko/logo.webp" alt="VOTE"><h1>Make them match it.</h1><p>Make a shot. Everyone else copies it.<br>Last player standing wins.</p><button class="mobile-primary" data-action="start">Play VOTE</button><div class="mobile-pick" hidden><h2>Who's got next?</h2><div class="mobile-players"></div><div class="mobile-modes" role="group" aria-label="Match mode"><button data-mode="solo">Solo<span>vs 2 computers</span></button><button data-mode="local">Pass & play<span>3 friends Â· 1 phone</span></button></div><button class="mobile-primary" data-action="court">Choose court</button></div></section><section class="mobile-hud" hidden aria-label="Match scores"><div class="mobile-scores"></div><p class="mobile-turn"></p><div class="mobile-meter" hidden aria-label="Shot timing"><span class="mobile-gold"></span><span class="mobile-needle"></span></div></section><section class="mobile-result" hidden><h2></h2><button class="mobile-primary" data-action="again">Play again</button><button data-action="newcourt">Choose court</button></section><p class="mobile-rotate" hidden>More court to play with? Turn your phone sideways.</p>`;
  document.body.append(root);
  const menu=root.querySelector('.mobile-menu'),pick=root.querySelector('.mobile-pick'),start=root.querySelector('[data-action=start]'),hud=root.querySelector('.mobile-hud'),scores=root.querySelector('.mobile-scores'),turn=root.querySelector('.mobile-turn'),meter=root.querySelector('.mobile-meter');
  let actions=null,last='';
  root.querySelector('[data-action=again]').addEventListener('click',()=>actions?.again());root.querySelector('[data-action=newcourt]').addEventListener('click',()=>actions?.court());
  start.addEventListener('click',()=>actions?.start());root.querySelector('[data-action=court]').addEventListener('click',()=>actions?.court());
  root.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>actions?.mode(button.dataset.mode)));
  window.VoteMobile={mount(config){actions=config;const players=root.querySelector('.mobile-players');config.roster.forEach((fighter,index)=>{const button=document.createElement('button');button.className='mobile-player';button.setAttribute('aria-label',fighter.full);button.innerHTML=`<canvas width="100" height="120" aria-hidden="true"></canvas><strong></strong>`;button.querySelector('strong').textContent=fighter.name;button.addEventListener('click',()=>config.pick(index));players.append(button);});},update(state){
    const enabled=document.documentElement.classList.contains('has-touch');root.hidden=!enabled;if(!enabled)return;
    const visibleMenu=!state.playing&&!state.overlay;menu.hidden=!visibleMenu;pick.hidden=state.screen!=='select';start.hidden=state.screen==='select';menu.querySelector('h1').hidden=state.screen==='select';menu.querySelector('p').hidden=state.screen==='select';menu.querySelector('.mobile-logo').hidden=state.screen==='select';
    root.querySelector('.mobile-rotate').hidden=!state.playing||state.overlay;hud.hidden=!state.playing||state.overlay;
    document.documentElement.classList.toggle('mobile-playing',state.playing);document.documentElement.classList.toggle('mobile-overlay',state.overlay);
    if(state.screen==='select'){root.querySelectorAll('.mobile-player').forEach((button,i)=>{button.setAttribute('aria-pressed',String(i===state.selected));const c=button.querySelector('canvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,100,120);actions.portrait(ctx,i);});root.querySelectorAll('[data-mode]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.mode===state.mode)));}
    const result=root.querySelector('.mobile-result');result.hidden=!state.winner||state.overlay;result.querySelector('h2').textContent=state.winner?`${state.winner} wins!`:"";
    if(!state.playing)return;
    const signature=JSON.stringify(state.players);if(signature!==last){last=signature;scores.replaceChildren();state.players.forEach(player=>{const card=document.createElement('div');card.className='mobile-score'+(player.active?' active':'')+(player.out?' out':'');const name=document.createElement('strong');name.textContent=player.name;card.append(name);const letters=document.createElement('span');for(let i=0;i<4;i++){const letter=document.createElement('b');letter.textContent='VOTE'[i];letter.className=i<player.letters?'earned':'';letters.append(letter);}card.append(letters);card.setAttribute('aria-label',`${player.name}, ${player.out?'out':player.letters+' letters'}${player.active?', current turn':''}`);scores.append(card);});}
    const text=state.message;if(turn.textContent!==text)turn.textContent=text;
    meter.hidden=!state.aiming;if(state.aiming){root.querySelector('.mobile-gold').style.left=`${Math.max(0,state.aiming.need-state.aiming.span)*100}%`;root.querySelector('.mobile-gold').style.width=`${state.aiming.span*200}%`;root.querySelector('.mobile-needle').style.left=`${state.power*100}%`;meter.classList.toggle('hit',state.aiming.hit);}
  }};
})();
